# Generated by Django 5.2.6 on 2025-09-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='FilmsAydSerials',
        ),
    ]
