# Generated by Django 5.2.6 on 2025-09-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0003_serials_rename_filmsaydserials_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films')),
            ],
        ),
        migrations.CreateModel(
            name='EntrySerials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('serials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_site.serials')),
            ],
        ),
    ]
