# Generated by Django 5.2.6 on 2025-09-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0004_entryfilms_entryserials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryFilms',
            new_name='EntryNameFilm',
        ),
        migrations.RenameField(
            model_name='entrynamefilm',
            old_name='films',
            new_name='films_name',
        ),
        migrations.RenameField(
            model_name='entrynamefilm',
            old_name='text',
            new_name='name_film',
        ),
        migrations.CreateModel(
            name='EntryGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('films_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films')),
            ],
        ),
    ]
