# Generated by Django 5.2.6 on 2025-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0005_rename_entryfilms_entrynamefilm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrynamefilm',
            name='genre',
            field=models.TextField(null=True),
        ),
    ]
