# Generated by Django 5.2.6 on 2025-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0006_entrynamefilm_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
