# Generated by Django 5.2.6 on 2025-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0007_films_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrynamefilm',
            old_name='name_film',
            new_name='about_film',
        ),
        migrations.RenameField(
            model_name='entryserials',
            old_name='text',
            new_name='about_serial',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='genre',
            new_name='director_film',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='text',
            new_name='name_film',
        ),
        migrations.RenameField(
            model_name='serials',
            old_name='text',
            new_name='name_serial',
        ),
        migrations.RemoveField(
            model_name='entrynamefilm',
            name='genre',
        ),
        migrations.AddField(
            model_name='films',
            name='genre_film',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='films',
            name='year_of_release_film',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serials',
            name='director_serial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serials',
            name='genre_serial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serials',
            name='year_of_release_serial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='EntryGenre',
        ),
    ]
