# Generated by Django 5.2.6 on 2025-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0008_rename_name_film_entrynamefilm_about_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director_film',
            field=models.CharField(blank=True, help_text='Режиссер', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='genre_film',
            field=models.CharField(blank=True, help_text='Жанр', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='name_film',
            field=models.CharField(help_text='Название фильма', max_length=200),
        ),
        migrations.AlterField(
            model_name='films',
            name='year_of_release_film',
            field=models.CharField(blank=True, help_text='Год создания', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serials',
            name='director_serial',
            field=models.CharField(blank=True, help_text='Режиссер', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serials',
            name='genre_serial',
            field=models.CharField(blank=True, help_text='Жанр', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serials',
            name='name_serial',
            field=models.CharField(help_text='Название сериала', max_length=200),
        ),
        migrations.AlterField(
            model_name='serials',
            name='year_of_release_serial',
            field=models.CharField(blank=True, help_text='Год создания', max_length=200, null=True),
        ),
    ]
