# Generated by Django 5.2.6 on 2025-09-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0009_alter_films_director_film_alter_films_genre_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genre_film',
            field=models.CharField(default='default_text', help_text='Жанр', max_length=200),
        ),
    ]
