# Generated by Django 5.2.6 on 2025-09-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0010_alter_films_genre_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genre_film',
            field=models.CharField(blank=True, help_text='Жанр', max_length=200, null=True),
        ),
    ]
