# Generated by Django 5.2.6 on 2025-09-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0011_alter_films_genre_film'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrySerials',
            new_name='EntryNameSerial',
        ),
    ]
