# Generated by Django 5.2.6 on 2025-10-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0013_alter_films_genre_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genre_film',
            field=models.CharField(blank=True, choices=[('1', 'детектив'), ('2', 'фанатастика'), ('3', 'мелодрама'), ('4', 'приключения'), ('5', 'боевик')], help_text='Жанр', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serials',
            name='genre_serial',
            field=models.CharField(blank=True, choices=[('1', 'детектив'), ('2', 'фанатастика'), ('3', 'мелодрама'), ('4', 'приключения'), ('5', 'боевик')], help_text='Жанр', max_length=200, null=True),
        ),
    ]
