# Generated by Django 5.2.6 on 2025-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0014_alter_films_genre_film_alter_serials_genre_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='film_serial',
            field=models.CharField(choices=[('1', 'film'), ('2', 'serial')], default=''),
        ),
    ]
