# Generated by Django 5.2.6 on 2025-10-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0015_films_film_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='film_serial',
            field=models.CharField(choices=[('film', 'film'), ('serial', 'serial')], default=''),
        ),
        migrations.AlterField(
            model_name='films',
            name='film_serial',
            field=models.CharField(choices=[('film', 'film'), ('serial', 'serial')], default=''),
        ),
    ]
