# Generated by Django 5.2.6 on 2025-10-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0016_serials_film_serial_alter_films_film_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='country_production_film',
            field=models.CharField(blank=True, help_text='Страна производства', max_length=200, null=True),
        ),
    ]
