# Generated by Django 5.2.6 on 2025-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0017_films_country_production_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='country_production_film',
            new_name='country_production',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='director_film',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='genre_film',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='films',
            old_name='year_of_release_film',
            new_name='year_of_release',
        ),
        migrations.RemoveField(
            model_name='films',
            name='name_film',
        ),
        migrations.AddField(
            model_name='films',
            name='name',
            field=models.CharField(default='', help_text='Название', max_length=200),
        ),
    ]
