# Generated by Django 5.2.6 on 2025-10-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0018_rename_country_production_film_films_country_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(help_text='Название', max_length=200),
        ),
    ]
