# Generated by Django 5.2.6 on 2025-10-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0019_alter_films_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.CharField(blank=True, choices=[('детектив', 'детектив'), ('фантастика', 'фанатастика'), ('мелодрама', 'мелодрама'), ('приключения', 'приключения'), ('боевик', 'боевик')], help_text='Жанр', max_length=200, null=True),
        ),
    ]
