# Generated by Django 5.2.6 on 2025-10-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0020_alter_films_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntryNameSerial',
        ),
        migrations.DeleteModel(
            name='Serials',
        ),
    ]
