# Generated by Django 5.2.6 on 2025-10-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0021_delete_entrynameserial_delete_serials'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='films',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text/'),
        ),
    ]
