# Generated by Django 5.2.6 on 2025-10-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0022_films_cover_films_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
