# Generated by Django 5.2.6 on 2025-10-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0023_alter_films_cover_alter_films_text_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='cover',
            new_name='image',
        ),
    ]
