# Generated by Django 5.2.6 on 2025-11-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0024_rename_cover_films_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='about_film',
            field=models.TextField(default=''),
        ),
    ]
