# Generated by Django 5.2.6 on 2025-11-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0025_alter_entrynamefilm_about_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='about_film',
            field=models.TextField(blank=True, null=True),
        ),
    ]
