# Generated by Django 5.2.6 on 2025-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0030_alter_entrynamefilm_films_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='about_film',
            field=models.TextField(),
        ),
    ]
