# Generated by Django 5.2.6 on 2025-11-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0031_alter_entrynamefilm_about_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='films_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films'),
        ),
    ]
