# Generated by Django 5.2.6 on 2025-11-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0032_alter_entrynamefilm_films_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='films_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films'),
        ),
    ]
