# Generated by Django 5.2.6 on 2025-11-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0033_alter_entrynamefilm_films_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrynamefilm',
            old_name='films_name',
            new_name='films',
        ),
    ]
