# Generated by Django 5.2.6 on 2025-11-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0034_rename_films_name_entrynamefilm_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrynamefilm',
            name='estimation',
            field=models.IntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], help_text='Оценка по пятибальной шкале', null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='genre',
            field=models.CharField(blank=True, choices=[('детектив', 'детектив'), ('фантастика', 'фанатастика'), ('мелодрама', 'мелодрама'), ('приключения', 'приключения'), ('боевик', 'боевик'), ('комедия', 'комедия')], help_text='Жанр', max_length=200, null=True),
        ),
    ]
