# Generated by Django 5.2.6 on 2025-11-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0035_entrynamefilm_estimation_alter_films_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='about_film',
            field=models.TextField(help_text='Добавьте комментарий к фильму'),
        ),
    ]
