# Generated by Django 5.2.6 on 2025-11-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0037_alter_entrynamefilm_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrynamefilm',
            name='estimation',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], help_text='Оценка по пятибальной шкале', null=True),
        ),
    ]
