# Generated by Django 5.2.6 on 2025-11-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0038_alter_entrynamefilm_estimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='image',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films')),
            ],
        ),
    ]
