# Generated by Django 5.2.6 on 2025-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0042_alter_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, help_text='Название', max_length=200, null=True),
        ),
    ]
