# Generated by Django 5.2.6 on 2025-12-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0044_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='directors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.directors'),
        ),
    ]
