# Generated by Django 5.2.6 on 2025-12-12 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0045_films_directors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='MediaFilm',
        ),
        migrations.RemoveField(
            model_name='films',
            name='director',
        ),
        migrations.AddField(
            model_name='directors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directors',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия режиссера', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MediaDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/directors/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('directors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.directors')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
