# Generated by Django 5.2.6 on 2025-12-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0046_rename_media_mediafilm_remove_films_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadirectors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
