# Generated by Django 5.2.6 on 2025-12-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0047_alter_mediadirectors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='directors',
            name='data_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True),
        ),
        migrations.AddField(
            model_name='directors',
            name='data_of_death',
            field=models.DateField(blank=True, help_text='Дата смерти', null=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='directors',
            field=models.ForeignKey(help_text='Режиссер', null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.directors'),
        ),
    ]
