# Generated by Django 5.2.6 on 2025-12-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0048_directors_data_of_birth_directors_data_of_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='directors',
            field=models.ForeignKey(help_text='Режиссер', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_site.directors'),
        ),
    ]
