# Generated by Django 5.2.6 on 2026-01-15 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0049_alter_films_directors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrynamefilm',
            name='estimation',
        ),
        migrations.CreateModel(
            name='EntryEstimationFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation', models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], help_text='Оценка по пятибальной шкале', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название', max_length=200, null=True)),
                ('videos', models.FileField(blank=True, help_text='Выберите файл для загрузки', null=True, upload_to='images/videos/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_site.films')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
