# Generated by Django 5.2.6 on 2026-01-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0050_remove_entrynamefilm_estimation_entryestimationfilm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofilm',
            name='videos',
            field=models.FileField(blank=True, help_text='Выберите файл для загрузки', null=True, upload_to='videos/'),
        ),
    ]
