# Generated by Django 5.2.6 on 2026-01-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0051_alter_videofilm_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofilm',
            name='videos',
            field=models.FileField(blank=True, help_text='Выберите файл для загрузки', null=True, upload_to='images/'),
        ),
    ]
