# Generated by Django 5.2.6 on 2026-01-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0052_alter_videofilm_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofilm',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
