# Generated by Django 5.2.6 on 2026-01-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0053_videofilm_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofilm',
            name='thumbnail',
        ),
    ]
